# Generated by Django 5.0.7 on 2024-08-01 10:25

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortal', '0002_userregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userregistration',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='email1',
            field=models.EmailField(default='abc@test.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='passwd',
            field=models.CharField(default='Pass@123', max_length=40),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='101', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='usernm',
            field=models.CharField(default='abc', max_length=40),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='class1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mobNo',
            field=models.CharField(max_length=13),
        ),
    ]
