# Generated by Django 5.0.7 on 2024-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortal', '0004_alter_userregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='age',
            field=models.PositiveIntegerField(max_length=3),
        ),
    ]
