# Generated by Django 5.0.7 on 2024-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examPortal', '0005_alter_userregistration_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
